### ISSUE TITLE
There is no examples folder

### ISSUE THREAD

**Issue by ZeeshanAbbas** [tilman151/rul-adapt#58]
Hi,
Thank you so much for providing the source code, but the examples folder is missing. Can you please update with the folder?

**Comment by tilman151** [comment]
Hey,
the examples folder was moved inside the [docs](github.com/tilman151/rul-adapt/docs/examples) folder. Also, you can have a look at the examples in the [docs website](https://krokotsch.eu/rul-adapt/examples/).

**Comment by ZeeshanAbbas** [comment]
Thank you so much for your response (Y)

**Comment by tilman151** [comment]
Updated README. The link should work now, too.
